import assert from 'node:assert/strict'
import { createIdle, toggleIdle, advanceIdle, catchUpIdle, restoreIdle, claimMemories, setIdleTide, setIdleRole, OFFLINE_CAP_SECONDS } from '../src/lighthouse/idle.mjs'

const state = createIdle()
assert.equal(advanceIdle(state, 300).rounds, 0, 'paused squads must not progress')
toggleIdle(state)
assert.equal(setIdleTide(state, 'down'), false)
assert.equal(setIdleRole(state, 0, 'warden'), false)
advanceIdle(state, 36)
assert.equal(state.game.mode, 'up')
assert.equal(state.game.status, 'finished')
assert.equal(state.bank, 5)
const checkpoint = restoreIdle(JSON.stringify(state))
assert.ok(checkpoint, 'valid checkpoint must restore')
advanceIdle(checkpoint, 1)
assert.equal(checkpoint.bank, 5, 'restoring a finished round must not duplicate rewards')
advanceIdle(state, 2)
assert.equal(state.game.mode, 'calm')
advanceIdle(state, 38)
assert.equal(state.game.mode, 'down')
advanceIdle(state, 48)
assert.equal(state.game.mode, 'up')
assert.equal(state.game.night, 4)
assert.equal(state.log.length, 3)
assert.ok(state.log.find(entry => entry.mode === 'down').success, 'default squad handles defense automatically')
const bank = state.bank
assert.ok(bank > 5)
assert.equal(claimMemories(state), bank)
assert.equal(claimMemories(state), 0, 'claim cannot pay twice')
assert.equal(state.memories, bank)
toggleIdle(state)
const paused = JSON.stringify(state)
advanceIdle(state, 7200)
assert.equal(JSON.stringify(state), paused)

const continuous = createIdle(), split = createIdle()
toggleIdle(continuous); toggleIdle(split)
advanceIdle(continuous, 420.37)
for (let i = 0; i < 420; i++) advanceIdle(split, 1)
advanceIdle(split, .37)
assert.deepEqual(split.game, continuous.game, 'frame timing and away progression must agree')
assert.deepEqual(split.log, continuous.log)
assert.equal(split.bank, continuous.bank)
assert.ok(Math.abs(split.remainder - continuous.remainder) < 1e-6)

const away = createIdle(), capped = createIdle()
toggleIdle(away); toggleIdle(capped)
away.lastSavedAt = 1_000_000
const now = away.lastSavedAt + 24 * 60 * 60 * 1000
const result = catchUpIdle(away, now)
advanceIdle(capped, OFFLINE_CAP_SECONDS)
assert.equal(result.seconds, OFFLINE_CAP_SECONDS)
assert.equal(away.bank, capped.bank)
assert.deepEqual(away.game, capped.game)
assert.equal(catchUpIdle(away, now).earned, 0, 'same timestamp cannot accrue twice')
assert.equal(catchUpIdle(away, now - 1000).seconds, 0, 'backward clock cannot simulate negative time')
assert.ok(restoreIdle(JSON.stringify(away)))
assert.equal(restoreIdle('broken json'), null)
assert.equal(restoreIdle(JSON.stringify({ ...away, bank: -1 })), null)
assert.equal(restoreIdle(JSON.stringify({ ...away, game: { ...away.game, roles: ['fake'] } })), null)
assert.equal(setIdleRole(state, 6, 'warden'), false)
assert.equal(setIdleTide(state, 'bogus'), false)
console.log(`Idle checks passed: automatic tide rotation, ${result.rounds} rounds in 2h, deterministic catch-up, pause, restore, and single claim.`)
